name: Test scheduled cron Jobs

on:
  schedule: 
    - cron: '30 1 * * SUN'

jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run every Sunday
        run: |
          echo cron job success
